### ISSUE TITLE
"prevalueSourceId" for form fields isn't serialized correctly

### ISSUE THREAD

**Issue by jaandrews** [KevinJump/uSync.Forms#10]
I got the following error when attempting to import a form using uSync 8.11.3 and uSync.Forms 8.0.1 in a site running umbraco 8.18.5 and UmbracoForms 8.11.0.
```
Import Fail: Error converting value "France Regions" to type 'System.Guid'. Path '[0].fieldSets[1].containers[0].fields[1].prevalueSourceId'.
```
The problem is that it's saving the name of the pre value source instead of its key for some reason. The deserialization logic still expects a guid though, hence this error. Pretty sure the problem line is [here](https://github.com/KevinJump/uSync.Forms/blob/master/uSync.Forms/Serializers/FormSerializer.cs#L142). Not sure whether there is a reason for this conversion.

I manually changed them to the correct guids in the config files and it imported correctly after that, so it seems that it's just the serialization that's the problem here.

**Comment by TheFogOfWar1** [comment]
@KevinJump I am also having this issue in umbraco 13.5.1 and usync.forms 13.3.0. Could you have look in to this?

**Comment by KevinJump** [comment]
Hi, 

What should happen (an i suspect fails when the pre-value is missing, hence the error) is the pre-value guid is replaced with the name on export and then on import the name is replaced with the relevant guid locally. 

this is because the guid values can change between sites (e.g. the keys are different). ordinarily we would set the key values on each end, but we don't here, because i think we can't / couldn't always. so that's why mapping exists. 

its something we should check for v13 though because if we can set the key we don't need to map it....

**Comment by KevinJump** [comment]
so yes, we can't set the value of the pre-value source, but we can put some better messaging and fail safes around it (which is what this pr does).

**Comment by KevinJump** [comment]
Hi, 

What should happen (an i suspect fails when the pre-value is missing, hence the error) is the pre-value guid is replaced with the name on export and then on import the name is replaced with the relevant guid locally. 

this is because the guid values can change between sites (e.g. the keys are different). ordinarily we would set the key values on each end, but we don't here, because i think we can't / couldn't always. so that's why the mapping exists. 

its something we should check for v13 though because if we can set the key we don't need to map it....

**Comment by KevinJump** [comment]
https://www.nuget.org/packages/uSync.Forms/13.4.0
