### ISSUE TITLE
Issue with sync pack

### ISSUE THREAD

**Issue by bielu** [KevinJump/uSync.Forms#15]
I am trying to sync forms between envs, and this works fine, however when I am trying sync prevalue sources it doesn't work.
So i though maybe generating sync pac is broken on this specific bit, but as far I can tell, there is no way to create complete sync pack for forms, as forms are not presented in exporter:

![image](https://github.com/user-attachments/assets/a92b212f-4d97-4cb3-a076-a5bf695b5192)

error on import:
Missing pack folder, C:\projects\EngUk-Corp-and-education\src\EngineeringUK.Sites\umbraco\Data\TEMP\uSync\exports\303b5d27-09bc-49fa-a79b-dc3ed29d9cc7\uSync this may be a load balancing issue?

**Comment by KevinJump** [comment]
Forms doesn't currently show on the exporter because forms doesn;t use standard picking dialogs :( so we can't open it using the code we have. Its something we are looking at (and i think we can do in v14 - because its all a bit more 'normal'). but at the moment not there.

other things is the pr, which hopefully i am about to merge
