### ISSUE TITLE
What version can I use with Umbraco V14?

### ISSUE THREAD

**Issue by PeeDeeWhite** [KevinJump/uSync.Forms#25]
Hi there,

I have a site with Umbraco.Cms 14.3.1 and uSync 14.2.3.  I want to add uSync.Forms but there is not a version that targets Umbraco 14. I looked at 13.4.2 but it has a dependcy on Umbraco.Cms.Web.Backoffice as so will not work with 14. Is there any plan to build a 14 version or are you expecting everyone will migrate to 15?  I am stuck at version 14 at present as my ISP is not upgrading to .NET 9 yet.

Cheers

Paul

**Comment by KevinJump** [comment]
Hi, 

Unfortunately we have skipped v14 for uSync forms . 

Basically, it took so long to upgrade everything else then when we got to it, v15 was already out :( 

Because we also updated a lot of internal code to work with the internal changes with v15 (Umbraco v15 also had big changes). it's not a non-trivial task to backport the v15 release to v14 - so I don't think its going to happen - sorry.

**Comment by PeeDeeWhite** [comment]
@KevinJump I understand, thanks for letting me know.  I might have to downgrade to v13 or live with the fact that I cannot sync my forms for now.  The site is not likely to change for a while anyway.
